//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextCallerApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NextCallerApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nc-Account-Id.
        /// </summary>
        internal static string AccountIdHeaderName {
            get {
                return ResourceManager.GetString("AccountIdHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account_id.
        /// </summary>
        internal static string AccountIdParameterName {
            get {
                return ResourceManager.GetString("AccountIdParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analyze/.
        /// </summary>
        internal static string AnalyzePath {
            get {
                return ResourceManager.GetString("AnalyzePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1.
        /// </summary>
        internal static string DefaultAPIVersion {
            get {
                return ResourceManager.GetString("DefaultAPIVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string EmailUrlParameterName {
            get {
                return ResourceManager.GetString("EmailUrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format.
        /// </summary>
        internal static string FormatUrlParameterName {
            get {
                return ResourceManager.GetString("FormatUrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fraud/.
        /// </summary>
        internal static string FraudPath {
            get {
                return ResourceManager.GetString("FraudPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        internal static string NameAddressAddressUrlParameterName {
            get {
                return ResourceManager.GetString("NameAddressAddressUrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        internal static string NameAddressCityUrlParameterName {
            get {
                return ResourceManager.GetString("NameAddressCityUrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first_name.
        /// </summary>
        internal static string NameAddressFirstNameUrlParameterName {
            get {
                return ResourceManager.GetString("NameAddressFirstNameUrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_name.
        /// </summary>
        internal static string NameAddressLastNameUrlParameterName {
            get {
                return ResourceManager.GetString("NameAddressLastNameUrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state.
        /// </summary>
        internal static string NameAddressStateUrlParameterName {
            get {
                return ResourceManager.GetString("NameAddressStateUrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip_code.
        /// </summary>
        internal static string NameAddressZipUrlParameterName {
            get {
                return ResourceManager.GetString("NameAddressZipUrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        internal static string PageParameterName {
            get {
                return ResourceManager.GetString("PageParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 559.
        /// </summary>
        internal static string PaginationExceptionCode {
            get {
                return ResourceManager.GetString("PaginationExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records/.
        /// </summary>
        internal static string PhonePath {
            get {
                return ResourceManager.GetString("PhonePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        internal static string PhoneUrlParameterName {
            get {
                return ResourceManager.GetString("PhoneUrlParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts/.
        /// </summary>
        internal static string PlatformPath {
            get {
                return ResourceManager.GetString("PlatformPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.sandbox.devel.nextcaller.com/.
        /// </summary>
        internal static string SandboxUrl {
            get {
                return ResourceManager.GetString("SandboxUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users/.
        /// </summary>
        internal static string UsersPath {
            get {
                return ResourceManager.GetString("UsersPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.devel.nextcaller.com/.
        /// </summary>
        internal static string WorkingUrl {
            get {
                return ResourceManager.GetString("WorkingUrl", resourceCulture);
            }
        }
    }
}
