//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextCallerApiTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NextCallerApiTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;error&quot;: {
        ///        &quot;message&quot;: &quot;There are validation errors:&quot;, 
        ///        &quot;code&quot;: &quot;1054&quot;, 
        ///        &quot;type&quot;: &quot;Validation&quot;, 
        ///        &quot;description&quot;: {
        ///            &quot;email&quot;: [
        ///                &quot;Invalid email address&quot;
        ///            ]
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string JsonError {
            get {
                return ResourceManager.GetString("JsonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;spoofed&quot;: &quot;false&quot;,
        ///  &quot;fraud_risk&quot;: &quot;low&quot;
        ///}.
        /// </summary>
        internal static string JsonFraudLevel {
            get {
                return ResourceManager.GetString("JsonFraudLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { 
        ///    &quot;platform_users&quot;: [ 
        ///        {  
        ///            &quot;created_time&quot;: &quot;2014­03­16T10:40:12&quot;, 
        ///            &quot;number_of_operations&quot;: 1, 
        ///            &quot;resource_uri&quot;: &quot;/api/v2/platform_users/pl2_un2/&quot;, 
        ///            &quot;total_calls&quot;: { 
        ///                &quot;201405&quot;: 2 
        ///            }, 
        ///            &quot;successful_calls&quot;: { 
        ///                &quot;201405&quot;: 1 
        ///            }, 
        ///            &quot;billable_calls&quot;: { }, 
        ///            &quot;username&quot;: &quot;pl2_un1&quot; 
        ///        }, 
        ///        { 
        ///            &quot;created_time&quot;: &quot;2014­04­16T13:42:00&quot;,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonPlatformStatistics {
            get {
                return ResourceManager.GetString("JsonPlatformStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;created_time&quot;: &quot;2014­04­16T13:42:00&quot;, 
        ///    &quot;number_of_operations&quot;: 24,  
        ///    &quot;resource_uri&quot;: &quot;/api/v2/platform_users/user12345/&quot;,  
        ///    &quot;total_calls&quot;: {  
        ///        &quot;201403&quot;: 7,  
        ///        &quot;201404&quot;: 12,  
        ///        &quot;201405&quot;: 10  
        ///    },  
        ///    &quot;successful_calls&quot;: {  
        ///        &quot;201403&quot;: 6,  
        ///        &quot;201404&quot;: 10,  
        ///        &quot;201405&quot;: 8  
        ///    },  
        ///    &quot;billable_calls&quot;: {  
        ///        &quot;201404&quot;: 1,  
        ///        &quot;201405&quot;: 1  
        ///    },  
        ///    &quot;username&quot;: &quot;user12345&quot;  
        /// }.
        /// </summary>
        internal static string JsonPlatformUser {
            get {
                return ResourceManager.GetString("JsonPlatformUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;97d949a413f4ea8b85e9586e1f2d9a&quot;,
        ///    &quot;first_name&quot;: &quot;Jerry&quot;,
        ///    &quot;last_name&quot;: &quot;Seinfeld&quot;,
        ///    &quot;name&quot;: &quot;Jerry Seinfeld&quot;,
        ///    &quot;language&quot;: &quot;English&quot;,
        ///    &quot;fraud_threat&quot;: &quot;low&quot;,
        ///    &quot;spoof&quot;: &quot;false&quot;,
        ///    &quot;phone&quot;: [
        ///        {
        ///            &quot;number&quot;: &quot;2125558383&quot;
        ///        }
        ///    ],
        ///    &quot;carrier&quot;: &quot;Verizon Wireless&quot;,
        ///    &quot;line_type&quot;: &quot;LAN&quot;,
        ///    &quot;address&quot;: [
        ///        {
        ///            &quot;city&quot;: &quot;New York&quot;,
        ///            &quot;extended_zip&quot;: &quot;&quot;,
        ///            &quot;country&quot;: &quot;USA&quot;,
        ///            &quot;line2&quot;: &quot;Apt 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonProfile {
            get {
                return ResourceManager.GetString("JsonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;records&quot;: [
        ///        {
        ///            &quot;id&quot;: &quot;97d949a413f4ea8b85e9586e1f2d9a&quot;,
        ///            &quot;first_name&quot;: &quot;Jerry&quot;,
        ///            &quot;last_name&quot;: &quot;Seinfeld&quot;,
        ///            &quot;name&quot;: &quot;Jerry Seinfeld&quot;,
        ///            &quot;language&quot;: &quot;English&quot;,
        ///            &quot;fraud_threat&quot;: &quot;low&quot;,
        ///            &quot;spoof&quot;: &quot;false&quot;,
        ///            &quot;phone&quot;: [
        ///                {
        ///                    &quot;number&quot;: &quot;2125558383&quot;
        ///                }
        ///            ], 
        ///            &quot;carrier&quot;: &quot;Verizon Wireless&quot;,
        ///            &quot;line_type&quot;: &quot;LAN&quot;,
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonProfiles {
            get {
                return ResourceManager.GetString("JsonProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;response&gt;
        ///    &lt;records&gt;
        ///        &lt;object&gt;
        ///            &lt;id&gt;97d949a413f4ea8b85e9586e1f2d9a&lt;/id&gt;
        ///            &lt;first_name&gt;Jerry&lt;/first_name&gt;
        ///            &lt;last_name&gt;Seinfeld&lt;/last_name&gt;
        ///            &lt;name&gt;Jerry Seinfeld&lt;/name&gt;
        ///            &lt;language&gt;English&lt;/language&gt;
        ///            &lt;fraud_threat&gt;low&lt;/fraud_threat&gt;
        ///            &lt;spoof&gt;false&lt;/spoof&gt;
        ///            &lt;phone&gt;
        ///                &lt;object&gt;
        ///                    &lt;number&gt;2125558383&lt;/number&gt;
        ///                &lt;/object&gt;
        ///            &lt;/phone&gt;
        ///            &lt;carr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlResponse {
            get {
                return ResourceManager.GetString("XmlResponse", resourceCulture);
            }
        }
    }
}
